import type { AvatarTone } from "@/components/ui/primitives";

export type ApplicantStatus = "pending" | "interview" | "approved" | "rejected" | "suspended";

export type Score = 1 | 2 | 3 | 4 | 5;
export type Evaluation = {
  fluency: Score;
  professionalism: Score;
  teaching: Score;
  camera: Score;
  internet: Score;
};

export type Applicant = {
  id: string;
  name: string;
  initials: string;
  tone: AvatarTone;
  email: string;
  phone: string;
  location: string; // "Portland, OR (PST)"
  city: string;
  applied: string; // ISO date, formatted per locale
  status: ApplicantStatus;
  flag?: "idPending" | "noVideo";
  videoLength: string | null;
  education: string;
  experienceYears: number; // 0 = less than 1 year
  teaches: string[]; // specialty names (keys of common.specialties)
  rate: number;
  certifications: string[];
  identity: { verified: true; document: "passport" | "driversLicense" } | { verified: false };
  evaluation: Evaluation;
  notes: string;
};

export const applicants: Applicant[] = [
  {
    id: "a-emily",
    name: "Emily Walker",
    initials: "EW",
    tone: "lilac",
    email: "emily.w@example.com",
    phone: "+1 (503) 000-0000",
    location: "Portland, OR (PST)",
    city: "Portland, OR",
    applied: "2026-10-12",
    status: "pending",
    videoLength: "1:54",
    education: "M.A. Linguistics",
    experienceYears: 6,
    teaches: ["Conversation", "Reading", "Teens"],
    rate: 30,
    certifications: ["TEFL.pdf", "Diploma.pdf"],
    identity: { verified: true, document: "passport" },
    evaluation: { fluency: 5, professionalism: 5, teaching: 4, camera: 4, internet: 5 },
    notes: "Warm, clear delivery. Good fit for Conversation and Teens.",
  },
  {
    id: "a-ryan",
    name: "Ryan Garcia",
    initials: "RG",
    tone: "sky",
    email: "ryan.garcia@example.com",
    phone: "+1 (305) 000-0000",
    location: "Miami, FL (EST)",
    city: "Miami, FL",
    applied: "2026-10-11",
    status: "pending",
    videoLength: "2:10",
    education: "B.A. English Literature",
    experienceYears: 4,
    teaches: ["Business English", "Travel"],
    rate: 32,
    certifications: ["TESOL.pdf"],
    identity: { verified: true, document: "driversLicense" },
    evaluation: { fluency: 5, professionalism: 4, teaching: 4, camera: 4, internet: 4 },
    notes: "",
  },
  {
    id: "a-tanya",
    name: "Tanya Nguyen",
    initials: "TN",
    tone: "orange",
    email: "tanya.nguyen@example.com",
    phone: "+1 (619) 000-0000",
    location: "San Diego, CA (PST)",
    city: "San Diego, CA",
    applied: "2026-10-10",
    status: "pending",
    flag: "idPending",
    videoLength: "1:32",
    education: "B.Ed. Secondary Education",
    experienceYears: 3,
    teaches: ["Teens", "General English"],
    rate: 25,
    certifications: ["TEFL.pdf"],
    identity: { verified: false },
    evaluation: { fluency: 5, professionalism: 4, teaching: 4, camera: 3, internet: 4 },
    notes: "Waiting for Stripe Identity result before review.",
  },
  {
    id: "a-chris",
    name: "Chris Bennett",
    initials: "CB",
    tone: "teal",
    email: "chris.bennett@example.com",
    phone: "+1 (404) 000-0000",
    location: "Atlanta, GA (EST)",
    city: "Atlanta, GA",
    applied: "2026-10-09",
    status: "pending",
    videoLength: "2:45",
    education: "M.A. TESOL",
    experienceYears: 9,
    teaches: ["IELTS Prep", "TOEFL Prep"],
    rate: 42,
    certifications: ["CELTA.pdf", "Diploma.pdf"],
    identity: { verified: true, document: "passport" },
    evaluation: { fluency: 5, professionalism: 5, teaching: 5, camera: 4, internet: 4 },
    notes: "",
  },
  {
    id: "a-laura",
    name: "Laura Hill",
    initials: "LH",
    tone: "yellow",
    email: "laura.hill@example.com",
    phone: "+1 (615) 000-0000",
    location: "Nashville, TN (CST)",
    city: "Nashville, TN",
    applied: "2026-10-08",
    status: "pending",
    flag: "noVideo",
    videoLength: null,
    education: "B.A. Communications",
    experienceYears: 2,
    teaches: ["Conversation"],
    rate: 22,
    certifications: ["TEFL.pdf"],
    identity: { verified: true, document: "passport" },
    evaluation: { fluency: 5, professionalism: 4, teaching: 3, camera: 3, internet: 4 },
    notes: "Asked to upload an introduction video.",
  },
  {
    id: "a-sarah",
    name: "Sarah Mitchell",
    initials: "SM",
    tone: "teal",
    email: "sarah.mitchell@example.com",
    phone: "+1 (512) 000-0000",
    location: "Austin, TX (CST)",
    city: "Austin, TX",
    applied: "2026-03-02",
    status: "approved",
    videoLength: "2:02",
    education: "B.A. Communications",
    experienceYears: 8,
    teaches: ["Business English", "Interview Prep", "Conversation"],
    rate: 35,
    certifications: ["TESOL.pdf"],
    identity: { verified: true, document: "passport" },
    evaluation: { fluency: 5, professionalism: 5, teaching: 5, camera: 5, internet: 5 },
    notes: "Top-rated. Featured on home page.",
  },
  {
    id: "a-amanda",
    name: "Amanda Lee",
    initials: "AL",
    tone: "sky",
    email: "amanda.lee@example.com",
    phone: "+1 (617) 000-0000",
    location: "Boston, MA (EST)",
    city: "Boston, MA",
    applied: "2026-02-18",
    status: "approved",
    videoLength: "1:48",
    education: "M.Ed. TESOL",
    experienceYears: 12,
    teaches: ["IELTS Prep", "TOEFL Prep"],
    rate: 45,
    certifications: ["CELTA.pdf", "M.Ed.pdf"],
    identity: { verified: true, document: "passport" },
    evaluation: { fluency: 5, professionalism: 5, teaching: 5, camera: 4, internet: 5 },
    notes: "",
  },
  {
    id: "a-david",
    name: "David King",
    initials: "DK",
    tone: "lilac",
    email: "david.king@example.com",
    phone: "+1 (720) 000-0000",
    location: "Denver, CO (MST)",
    city: "Denver, CO",
    applied: "2026-04-05",
    status: "approved",
    videoLength: "1:20",
    education: "B.A. Education",
    experienceYears: 3,
    teaches: ["Teens", "General English"],
    rate: 22,
    certifications: ["TEFL.pdf"],
    identity: { verified: true, document: "driversLicense" },
    evaluation: { fluency: 5, professionalism: 3, teaching: 4, camera: 4, internet: 3 },
    notes: "3rd cancellation this month — automatic warning sent.",
  },
  {
    id: "a-mark",
    name: "Mark Evans",
    initials: "ME",
    tone: "sand",
    email: "mark.evans@example.com",
    phone: "+1 (602) 000-0000",
    location: "Phoenix, AZ (MST)",
    city: "Phoenix, AZ",
    applied: "2026-09-28",
    status: "rejected",
    videoLength: "0:48",
    education: "High school diploma",
    experienceYears: 0,
    teaches: ["Conversation"],
    rate: 20,
    certifications: [],
    identity: { verified: true, document: "passport" },
    evaluation: { fluency: 4, professionalism: 3, teaching: 2, camera: 2, internet: 3 },
    notes: "No teaching certification; audio quality too low in video.",
  },
  {
    id: "a-kevin",
    name: "Kevin Price",
    initials: "KP",
    tone: "orange",
    email: "kevin.price@example.com",
    phone: "+1 (215) 000-0000",
    location: "Philadelphia, PA (EST)",
    city: "Philadelphia, PA",
    applied: "2026-01-30",
    status: "suspended",
    videoLength: "1:36",
    education: "B.A. History",
    experienceYears: 5,
    teaches: ["General English", "Travel"],
    rate: 28,
    certifications: ["TEFL.pdf"],
    identity: { verified: true, document: "passport" },
    evaluation: { fluency: 5, professionalism: 2, teaching: 4, camera: 4, internet: 3 },
    notes: "Suspended after repeated no-shows (Sep). Review in 30 days.",
  },
];
